### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by dlupu** [hexagonalconsulting/react-graceful-unmount#1]
1) the section `What may be impeding the componentWillUnmount from being called` could induce people in error : to my knowledge we do not cover the case of dom element being removed by jquery. we only cover hose 2 events mentionned in `How it works` section

2) in the example, please add a function `componentWillUnmount` with a code comment : `this function will always be called`

**Comment by this-miguel** [comment]
`we do not cover the case of dom element being removed by jquery` I thought that was precisely what we were doing
![screenshot from 2017-10-18 17-44-00](https://user-images.githubusercontent.com/15721544/31744242-16b3e7ac-b42c-11e7-96e4-2a3fb60d093c.png)
![screenshot from 2017-10-18 17-49-22](https://user-images.githubusercontent.com/15721544/31744441-c5691c18-b42c-11e7-9177-a08f48c9852c.png)
I thought that this dropdown triggered those XHR request and then the html in the response was rendered with jquery, so then the html is rendered as a normal request by the browser? could we add that functionality :) ?

**Comment by this-miguel** [comment]
you were right I did a test and send you a video of it via slack.

**Comment by this-miguel** [comment]
you are right, I removed that part of the README for now, later if we implement that feature, we could add it as an anotation letting people know that the package also solves that problem.
